# .github/CONTRIBUTING.yml

name: Contributing to LeetHub Sync

description: Guidelines for contributing to the LeetHub Sync project.

fields:
  - type: markdown
    attributes:
      value: |
        ## How to Contribute

        We appreciate your interest in contributing to **LeetHub Sync**. Please follow the guidelines below to help us manage and review contributions effectively.

  - type: markdown
    attributes:
      value: |
        ### Reporting Issues

        1. **Search for Existing Issues:** Before creating a new issue, check if it has already been reported by searching the [issue tracker](https://github.com/your-repo/LeetHub-Sync/issues).

        2. **Create a New Issue:** If the issue has not been reported, create a new issue by navigating to the [issues page](https://github.com/your-repo/LeetHub-Sync/issues/new). Use one of the provided issue templates to ensure you include all relevant information.

  - type: markdown
    attributes:
      value: |
        ### Submitting Changes

        1. **Fork the Repository:** Fork the repository to your own GitHub account and clone it to your local machine.

        2. **Create a Branch:** Create a new branch for your changes. Use a descriptive name for your branch that reflects the nature of the changes you are making (e.g., `fix-bug-in-sync-feature` or `add-new-option-to-settings`).

           ```bash
           git checkout -b your-branch-name
           ```

        3. **Make Changes:** Implement your changes in the new branch. Make sure to write clear and concise commit messages that describe the changes made.

        4. **Test Your Changes:** Run any tests to ensure that your changes do not break existing functionality. Add new tests if necessary.

        5. **Commit Your Changes:**

           ```bash
           git add .
           git commit -m "Description of changes"
           ```

        6. **Push to Your Fork:** Push your changes to your forked repository.

           ```bash
           git push origin your-branch-name
           ```

        7. **Create a Pull Request:** Navigate to the original repository and create a pull request from your branch. Provide a clear description of your changes and any relevant information that reviewers may need.

  - type: markdown
    attributes:
      value: |
        ### Code of Conduct

        By participating in this project, you agree to adhere to our [Code of Conduct](https://github.com/your-repo/LeetHub-Sync/blob/main/CODE_OF_CONDUCT.md). Please ensure that your interactions are respectful and constructive.

  - type: markdown
    attributes:
      value: |
        ## Additional Resources

        - [Contribution Guidelines](https://github.com/your-repo/LeetHub-Sync/blob/main/CONTRIBUTING.md)
        - [Issue Templates](https://github.com/your-repo/LeetHub-Sync/issues/new/choose)
        - [Pull Request Templates](https://github.com/your-repo/LeetHub-Sync/pulls)
