name: Bug Report
description: Create a report for a bug
title: "[Bug] "
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Upload screenshots here...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Choose your operating system
      options:
        - Windows
        - MacOS
        - Linux
        - Other

  - type: dropdown
    id: version
    attributes:
      label: LH Version
      description: LeetHub Sync Version Number
      options:
        - 1.1
        - 1.1
        - 1.2

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Add additional context here...
