name: Enhancement Request
description: Request an enhancement or new feature
title: "[Enhancement] "
labels: enhancement
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the enhancement or new feature.
      placeholder: Describe the enhancement or feature here...

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this enhancement or feature is needed.
      placeholder: Describe the motivation behind the request here...

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits or improvements do you expect from this enhancement?
      placeholder: Describe the expected benefits here...

  - type: textarea
    id: potential_implementation
    attributes:
      label: Potential Implementation
      description: Any ideas on how this enhancement could be implemented.
      placeholder: Describe potential implementation ideas here...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Indicate the priority level of this enhancement request.
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Choose your operating system (if relevant).
      options:
        - Windows
        - MacOS
        - Linux
        - Other

  - type: dropdown
    id: version
    attributes:
      label: LH Version
      description: LeetHub Sync Version Number (if applicable).
      options:
        - 1.0
        - 1.1
        - 1.2

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or relevant information here.
      placeholder: Add additional context here...
