name: Enhancement Request
description: Suggest an enhancement or new feature
title: "[Enhancement] "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        **Describe the enhancement**
        A clear and concise description of what you want to happen.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the enhancement here...

  - type: markdown
    attributes:
      value: |
        **Current behavior**
        A clear and concise description of what happens currently.
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: A clear and concise description of what happens currently.
      placeholder: Describe the current behavior here...

  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expect to happen.
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expect to happen.
      placeholder: Describe the expected behavior here...

  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain your suggestion.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your suggestion.
      placeholder: Upload screenshots here...

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context or ideas about the enhancement here.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or ideas about the enhancement here.
      placeholder: Add additional context here...
